/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-10-28 at 14:26:35 UTC 
 * Modify at your own risk.
 */

package com.appspot.thassculptures.sculptures.model;

/**
 * Model definition for Artist.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the sculptures. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Artist extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String entityKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String fname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String image;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String lname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("website_url")
  private String websiteUrl;

  /**
   * @return value or {@code null} for none
   */
  public String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public Artist setDescription(String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getEntityKey() {
    return entityKey;
  }

  /**
   * @param entityKey entityKey or {@code null} for none
   */
  public Artist setEntityKey(String entityKey) {
    this.entityKey = entityKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getFname() {
    return fname;
  }

  /**
   * @param fname fname or {@code null} for none
   */
  public Artist setFname(String fname) {
    this.fname = fname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getImage() {
    return image;
  }

  /**
   * @param image image or {@code null} for none
   */
  public Artist setImage(String image) {
    this.image = image;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getLname() {
    return lname;
  }

  /**
   * @param lname lname or {@code null} for none
   */
  public Artist setLname(String lname) {
    this.lname = lname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getWebsiteUrl() {
    return websiteUrl;
  }

  /**
   * @param websiteUrl websiteUrl or {@code null} for none
   */
  public Artist setWebsiteUrl(String websiteUrl) {
    this.websiteUrl = websiteUrl;
    return this;
  }

  @Override
  public Artist set(String fieldName, Object value) {
    return (Artist) super.set(fieldName, value);
  }

  @Override
  public Artist clone() {
    return (Artist) super.clone();
  }

}
